### ISSUE TITLE
i have some questions.

### ISSUE THREAD

**Issue by pervin0527** [huyquoctrinh/MetaPolyp-CBMS2023#4]
Hello. Firstly, thank you for sharing your excellent research and results.
I am currently participating in the BKAI-NeoPolyp competition on Kaggle and have a few questions.

There are some differences between the content in the paper and the code (e.g., Cosine annealing, input data normalization method, etc.). Is the reason for the difference in the code because it produced better results than what's mentioned in the paper?

In the paper, you performed a Binary task segmenting the area of the polyp. I am conducting Multi-class segmentation distinguishing between neopolyp and non-neopolyp. There's a significant gap in the detection rate, and for Multi-class, it doesn't match the performance mentioned in the paper. Why might that be?

Are you familiar with the BKAI-IGH small dataset? This dataset was created in Vietnam, and I heard there's a Large dataset, but I couldn't find it. Do you know how to obtain that dataset by any chance?

**Comment by huyquoctrinh** [comment]
Hi dear,

Thank you so much for your question, and for choosing the implementation, I chose the new one because after carefully tuning, this setup finds better performance.

Moreover, the drop in performance in the Multi-class segmentation of neopolyp, may be caused by the multi-polyp, which is the deficiency of our method. But maybe you can do the tuning for better results. Regarding BKAI-IGH, maybe you can send the email to the author of dataset, and they will have the response then.

**Comment by pervin0527** [comment]
Thank you for your good answer. It was very helpful.
